version: '3'

services:
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8.2
    restart: on-failure
    ports:
    - 2181:2181
    volumes:
    - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  
  kafka:
    image: bitnami/kafka:3.3.2
    ports:
    - 9092:9092
    restart: on-failure
    volumes:
    - kafka_data:/bitnami
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
    - zookeeper
  
volumes:
  zookeeper_data:
  kafka_data:

networks:
  cqrs-net: