version: '3'

services:
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8.2
    ports:
    - "2181:2181"
    volumes:
    - zookeeper_data:/bitnami
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
    - cqrs-net
  
  kafka:
    image: docker.io/bitnami/kafka:3.3.2
    ports:
    - "9092:9092"
    volumes:
    - kafka_data:/bitnami
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
    - zookeeper
    networks:
    - cqrs-net
  
  mongodb:
    image: docker.io/mongo:6.0
    ports:
    - "27017:27017"
    restart: on-failure
    volumes:
    - mongo_data:/data/db
    networks:
    - cqrs-net
  
  postgresql:
    image: docker.io/postgres:15-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: cqrs
      POSTGRES_USER: cqrs
      POSTGRES_PASSWORD: cqrs
    volumes:
    - pg_data:/var/lib/postgresql/data
    networks:
    - cqrs-net

volumes:
  zookeeper_data:
  kafka_data:
  mongo_data:
  pg_data:

networks:
  cqrs-net: