server:
  port: 5001

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:cqrs}
    username: ${POSTGRES_USER:cqrs}
    password: ${POSTGRES_PASSWORD:cqrs}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      group-id: bankAccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'